-- MySQL Script generated by MySQL Workbench
-- Вс 10 мая 2020 19:21:43
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema saitznak
-- -----------------------------------------------------
-- БД сайта знакомств
DROP SCHEMA IF EXISTS `saitznak` ;

-- -----------------------------------------------------
-- Schema saitznak
--
-- БД сайта знакомств
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `saitznak` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `saitznak` ;

-- -----------------------------------------------------
-- Table `adminblockedlog`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `adminblockedlog` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `adminblockedlog` (
  `nom` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(255) NOT NULL COMMENT 'логин',
  `blocked` TINYINT NULL COMMENT 'по умолчанию 0 - не заблокирован',
  PRIMARY KEY (`nom`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'кого заблокировал администратор по полученной жалобе или по другой причине';

SHOW WARNINGS;
CREATE UNIQUE INDEX `login` ON `adminblockedlog` (`login` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `anketa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `anketa` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `anketa` (
  `nomp` INT NOT NULL AUTO_INCREMENT,
  `loginp` VARCHAR(255) NOT NULL COMMENT 'логин',
  `zanyatiya` TEXT NOT NULL COMMENT 'занятие',
  `prozhivanie` TEXT NOT NULL COMMENT 'проживание',
  `uvlechenie` TEXT NOT NULL COMMENT 'увлечения',
  `dopolnitelno` TEXT NOT NULL COMMENT 'дополнительно',
  PRIMARY KEY (`nomp`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'таблица для анкеты для пользователей, показывает информацию о пользователе в повседневной жизни';

SHOW WARNINGS;
CREATE UNIQUE INDEX `loginp_UNIQUE` ON `anketa` (`loginp` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `druzyainet`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `druzyainet` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `druzyainet` (
  `nom` INT NOT NULL AUTO_INCREMENT,
  `moy` VARCHAR(255) NOT NULL COMMENT 'кому',
  `drug` VARCHAR(255) NOT NULL COMMENT 'друзья',
  `net` TINYINT(4) NOT NULL COMMENT 'черный список',
  `da` TINYINT(4) NOT NULL,
  PRIMARY KEY (`nom`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'пользователи могут разрешать другим пользователям из списка заходить на свою страницу, если она закрыта ото всех';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `finansy`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `finansy` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `finansy` (
  `nomp` INT NOT NULL AUTO_INCREMENT,
  `loginp` VARCHAR(255) NULL,
  `summa` INT NULL,
  PRIMARY KEY (`nomp`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'таблица с количеством условных единиц на счету каждого пользователя';

SHOW WARNINGS;
CREATE UNIQUE INDEX `login_UNIQUE` ON `finansy` (`loginp` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `forgostey`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `forgostey` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `forgostey` (
  `nom` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(255) NOT NULL COMMENT 'моя',
  `login_q` VARCHAR(255) NOT NULL COMMENT 'кто заходил',
  `data` DATETIME NOT NULL,
  PRIMARY KEY (`nom`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'кто из пользователей заходил на страницу другого пользователя и когда';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `fototabl`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fototabl` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `fototabl` (
  `nom` INT NOT NULL AUTO_INCREMENT COMMENT 'номер фото',
  `loginp` VARCHAR(255) NOT NULL COMMENT 'логин пользователя',
  `foto` VARCHAR(255) NOT NULL COMMENT 'имя фото',
  `metka` VARCHAR(10) NOT NULL COMMENT 'указатель на главную фотографию',
  `opisanie` VARCHAR(255) NOT NULL COMMENT 'описание от пользователя',
  `ponravilos` TEXT NULL COMMENT 'список логинов которым понравилось фото',
  `data` DATETIME NOT NULL,
  PRIMARY KEY (`nom`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'перечень фотографий у каждого пользователя';

SHOW WARNINGS;
CREATE FULLTEXT INDEX `ponravilos` ON `fototabl` (`ponravilos`) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `goroda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `goroda` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `goroda` (
  `nom` INT NOT NULL AUTO_INCREMENT,
  `region` VARCHAR(255) NOT NULL COMMENT 'регион',
  PRIMARY KEY (`nom`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'просто список всех регионов РФ';

SHOW WARNINGS;
CREATE UNIQUE INDEX `region` ON `goroda` (`region` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `lichnoe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lichnoe` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `lichnoe` (
  `nomp` INT NOT NULL AUTO_INCREMENT,
  `loginp` VARCHAR(255) NOT NULL COMMENT 'логин пользователя',
  `imya` VARCHAR(255) NOT NULL COMMENT 'имя',
  `region` VARCHAR(255) NOT NULL,
  `gorod` VARCHAR(255) NOT NULL,
  `datarozd` DATE NOT NULL,
  `metkap` TINYINT(4) NOT NULL COMMENT 'группа',
  `ipp` VARCHAR(255) NOT NULL COMMENT 'ip пользователя',
  `limitfoto` TINYINT(4) NOT NULL COMMENT 'количество фото',
  `semeynpolozh` VARCHAR(255) NOT NULL COMMENT 'замужем/незамужем',
  `pol` VARCHAR(7) NOT NULL COMMENT 'пол человека',
  PRIMARY KEY (`nomp`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'персональные данные для каждого из пользователей, используется для вывода информации в личном кабинете';

SHOW WARNINGS;
CREATE UNIQUE INDEX `loginp` ON `lichnoe` (`loginp` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `metki`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `metki` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `metki` (
  `nomp` INT NOT NULL AUTO_INCREMENT,
  `loginp` VARCHAR(255) NOT NULL,
  `metka` VARCHAR(45) NULL,
  PRIMARY KEY (`nomp`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Таблица с метками, показывает закрыл ли пользователь свой аккаунт от других пользователей';

SHOW WARNINGS;
CREATE UNIQUE INDEX `login_p` ON `metki` (`loginp` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `online`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `online` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `online` (
  `nomp` INT NOT NULL,
  `loginp` VARCHAR(255) NOT NULL,
  `idsession` VARCHAR(255) NOT NULL,
  `vremya` DATETIME NOT NULL,
  `online` TINYINT NULL DEFAULT 0 COMMENT 'по умолчанию 0, т.е. не онлайн. Если онлайн, то 1',
  PRIMARY KEY (`nomp`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'онлайн пользователь или нет';

SHOW WARNINGS;
CREATE UNIQUE INDEX `login` ON `online` (`loginp` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `polzovateli`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `polzovateli` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `polzovateli` (
  `nomp` INT NOT NULL AUTO_INCREMENT COMMENT 'номер пользователя, является первичным ключом',
  `loginp` VARCHAR(255) NOT NULL COMMENT 'логин',
  `parp` VARCHAR(255) NOT NULL COMMENT 'пароль',
  `vrepar` VARCHAR(255) NOT NULL COMMENT 'временный пароль',
  `timeregistr` DATETIME NOT NULL COMMENT 'дата регистрации',
  `proveren` TINYINT(4) NOT NULL COMMENT 'подтверждение логина',
  PRIMARY KEY (`nomp`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'главная таблица, данные для регистрации пользователя, входа на сайт, восстановления доступа';

SHOW WARNINGS;
CREATE INDEX `nomp_2` ON `polzovateli` (`nomp` ASC) VISIBLE;

SHOW WARNINGS;
CREATE UNIQUE INDEX `loginp_UNIQUE` ON `polzovateli` (`loginp` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `regiongorod`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `regiongorod` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `regiongorod` (
  `nom` INT NOT NULL AUTO_INCREMENT COMMENT 'номер',
  `region` VARCHAR(255) NOT NULL,
  `gorod` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`nom`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'все поселения и города в каждом из регионов';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `soobsheniya`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `soobsheniya` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `soobsheniya` (
  `nomer` INT NOT NULL AUTO_INCREMENT COMMENT 'номер сообщения',
  `otkogo` VARCHAR(255) NOT NULL,
  `komu` VARCHAR(255) NOT NULL,
  `soobshenie` TEXT NOT NULL,
  `data` DATETIME NOT NULL,
  `otmetka` TINYINT(4) NOT NULL DEFAULT '0' COMMENT 'по умолчанию 0 не прочитано',
  PRIMARY KEY (`nomer`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'таблица сообщений которые пишут пользователи друг другу';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `statusp`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `statusp` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `statusp` (
  `nomp` INT NOT NULL AUTO_INCREMENT,
  `loginp` VARCHAR(255) NOT NULL,
  `texts` TEXT NOT NULL COMMENT 'мысль вслух',
  `data` DATETIME NOT NULL,
  PRIMARY KEY (`nomp`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'последний статус каждого из пользователей';

SHOW WARNINGS;
CREATE UNIQUE INDEX `loginp_UNIQUE` ON `statusp` (`loginp` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `threetimesblock`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `threetimesblock` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `threetimesblock` (
  `nomp` INT NOT NULL AUTO_INCREMENT,
  `loginp` VARCHAR(255) NOT NULL,
  `ip` VARCHAR(255) NOT NULL,
  `timer` DATETIME NOT NULL,
  `parol` VARCHAR(255) NOT NULL,
  `times` TINYINT(4) NOT NULL,
  PRIMARY KEY (`nomp`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'таблица считающая попытки входа пользователей в систему, если неуспешно более 3 раз то блокируется на 15 минут, если успешно, то равна 0';

SHOW WARNINGS;
CREATE UNIQUE INDEX `loginr` ON `threetimesblock` (`loginp` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `zalobyna`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zalobyna` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `zalobyna` (
  `nom` INT NOT NULL AUTO_INCREMENT,
  `login_q` VARCHAR(255) NOT NULL,
  `login` VARCHAR(255) NOT NULL,
  `vremya` DATETIME NOT NULL,
  `prichina` VARCHAR(255) NOT NULL COMMENT 'причина жалобы',
  PRIMARY KEY (`nom`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'если пользователь жалуется на другого пользователя';

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
